In [165]:
##Working Notebook - Not Complete.

In [166]:
# Import required libraries.
import numpy as np

In [167]:
# Initialize the matrix with zeros to set the same.

chess_game = np.zeros((1, 8, 8, 32), dtype=int)
print(chess_game.shape)

(1, 8, 8, 32)


In [168]:
# Set pieces first before setting piece types.
# Dimension 0: Move 0.
# Dimension 1: Rank 0-8 is 1 to 8 as per conventional chess board.
# Dimension 2: File 0-8 is A to H as per conventional chess board.
# Dimension 3: 
#    0-15 (White): 0.K, 1.Q, 2.BF, 3.KG, 4.RH, 5.BC, 6.KB, 7.RA, 8.PA, 9.PB, 10.PC, 11.PD, 12.PE, 13.PF, 14.PG, 15.PH
#    16-31 (Black): 16.K, 17.Q, 18.BF, 19.KG, 20.RH, 21.BC, 22.KB, 23.RA, 24.PA, 25.PB, 26.PC, 27.PD, 28.PE, 29.PF, 30.PG, 31.PH

# WHITE PIECES - STARTING POSITION
chess_game[0,0,0,7] = 1   #RA  ( 7)
chess_game[0,0,1,6] = 1   #KB  ( 6)
chess_game[0,0,2,5] = 1   #BC  ( 5)
chess_game[0,0,3,1] = 1   #Q   ( 1)
chess_game[0,0,4,0] = 1   #K   ( 0)
chess_game[0,0,5,2] = 1   #BF  ( 2)
chess_game[0,0,6,3] = 1   #KG  ( 3)
chess_game[0,0,7,4] = 1   #RH  ( 4)
chess_game[0,1,0,8] = 1   #PA  ( 8)
chess_game[0,1,1,9] = 1   #PB  ( 9)
chess_game[0,1,2,10] = 1  #PC  (10)
chess_game[0,1,3,11] = 1  #PD  (11)
chess_game[0,1,4,12] = 1  #PE  (12)
chess_game[0,1,5,13] = 1  #PF  (13)
chess_game[0,1,6,14] = 1  #PG  (14)
chess_game[0,1,7,15] = 1  #PH  (15)

# BLACK PIECES - STARTING POSITION
chess_game[0,7,0,23] = 1  #RA  (23)
chess_game[0,7,1,22] = 1  #KB  (22)
chess_game[0,7,2,21] = 1  #BC  (21)
chess_game[0,7,3,17] = 1  #Q   (17)
chess_game[0,7,4,16] = 1  #K   (16)
chess_game[0,7,5,18] = 1  #BF  (18)
chess_game[0,7,6,19] = 1  #KG  (19)
chess_game[0,7,7,20] = 1  #RH  (20)
chess_game[0,6,0,24] = 1  #PA  (24)
chess_game[0,6,1,25] = 1  #PB  (25)
chess_game[0,6,2,26] = 1  #PC  (26)
chess_game[0,6,3,27] = 1  #PD  (27)
chess_game[0,6,4,28] = 1  #PE  (28)
chess_game[0,6,5,29] = 1  #PF  (29)
chess_game[0,6,6,30] = 1  #PG  (30)
chess_game[0,6,7,31] = 1  #PH  (31)

# Now we have a chess game with an opening board set out!

In [169]:
# Initialize the feature matrix with zeros to set the same.

piece_features = np.zeros((32,11), dtype=int)
print(piece_features.shape)

(32, 11)


In [170]:
# Set Active Indicator, First Move Indicator and Promoted Flag.
for i in range(32):
    piece_features[i,0] = 1  # Active Indicator
    piece_features[i,1] = 0  # First Move Indicator.  Redundant if initialized to 0.
    piece_features[i,10] = 0 # Promoted Flag.  Redundant if initialized to 0.

# Set Piece Color
#    0-15 (White): 0.K, 1.Q, 2.BF, 3.KG, 4.RH, 5.BC, 6.KB, 7.RA, 8.PA, 9.PB, 10.PC, 11.PD, 12.PE, 13.PF, 14.PG, 15.PH
#    16-31 (Black): 16.K, 17.Q, 18.BF, 19.KG, 20.RH, 21.BC, 22.KB, 23.RA, 24.PA, 25.PB, 26.PC, 27.PD, 28.PE, 29.PF, 30.PG, 31.PH
#    REMOVED: 32-39 (White): 32.PA-P, 33.PB-P, 34.PC-P, 35.PD-P, 36.PE-P, 37.PF-P, 38.PG-P, 39.PH-P
#    REMOVED: 40-47 (Black): 40.PA-P, 41.PB-P, 42.PC-P, 43.PD-P, 44.PE-P, 45.PF-P, 46.PG-P, 47.PH-P
for i in range(32):
    if i < 16:
        piece_features[i,2] = 1  # White
    else:
        piece_features[i,2] = 0  # Black

for i in range(32):
    if (i == 0) or (i == 16):      # King
        piece_features[i,3] = 1
    elif (i == 1) or (i == 17):    # Queen
        piece_features[i,4] = 1
    elif (i == 2) or (i == 21):    # White Bishop
        piece_features[i,5] = 1
    elif (i == 5) or (i == 18):    # Black Bishop
        piece_features[i,6] = 1
    elif (i == 3) or (i == 6) or (i == 19) or (i == 22):    # Knight
        piece_features[i,7] = 1
    elif (i == 4) or (i == 7) or (i == 20) or (i == 23):    # Rook
        piece_features[i,8] = 1
    else:
        piece_features[i,9] = 1 # Pawn

In [171]:
#TEST MOVE 1

chess_move = np.zeros((1, 8, 8, 32), dtype=int)

chess_move[0,0,0,7] = 1   #RA  ( 7)
chess_move[0,0,1,6] = 1   #KB  ( 6)
chess_move[0,0,2,5] = 1   #BC  ( 5)
chess_move[0,0,3,1] = 1   #Q   ( 1)
chess_move[0,0,4,0] = 1   #K   ( 0)
chess_move[0,0,5,2] = 1   #BF  ( 2)
chess_move[0,0,6,3] = 1   #KG  ( 3)
chess_move[0,0,7,4] = 1   #RH  ( 4)
chess_move[0,2,0,8] = 1   #PA  ( 8)
chess_move[0,1,1,9] = 1   #PB  ( 9)
chess_move[0,1,2,10] = 1  #PC  (10)
chess_move[0,1,3,11] = 1  #PD  (11)
chess_move[0,1,4,12] = 1  #PE  (12)
chess_move[0,1,5,13] = 1  #PF  (13)
chess_move[0,1,6,14] = 1  #PG  (14)
chess_move[0,1,7,15] = 1  #PH  (15)

# BLACK PIECES - STARTING POSITION
chess_move[0,7,0,23] = 1  #RA  (23)
chess_move[0,7,1,22] = 1  #KB  (22)
chess_move[0,7,2,21] = 1  #BC  (21)
chess_move[0,7,3,17] = 1  #Q   (17)
chess_move[0,7,4,16] = 1  #K   (16)
chess_move[0,7,5,18] = 1  #BF  (18)
chess_move[0,7,6,19] = 1  #KG  (19)
chess_move[0,7,7,20] = 1  #RH  (20)
chess_move[0,6,0,24] = 1  #PA  (24)
chess_move[0,6,1,25] = 1  #PB  (25)
chess_move[0,6,2,26] = 1  #PC  (26)
chess_move[0,6,3,27] = 1  #PD  (27)
chess_move[0,6,4,28] = 1  #PE  (28)
chess_move[0,6,5,29] = 1  #PF  (29)
chess_move[0,6,6,30] = 1  #PG  (30)
chess_move[0,6,7,31] = 1  #PH  (31)

In [172]:
chess_game = np.append(chess_game, chess_move, axis=0)

In [173]:
#  Some testing code.
#  Set these parameters and run the cell.
move = 0
rank = 2
file = 1


chess_game_class = np.argmax(chess_game, axis=-1)
print(chess_game_class[move,7])
print(chess_game_class[move,6])
print(chess_game_class[move,5])
print(chess_game_class[move,4])
print(chess_game_class[move,3])
print(chess_game_class[move,2])
print(chess_game_class[move,1])
print(chess_game_class[move,0])

print('One-Hot for Move ' +str(move) + ', Rank: ' +str(rank) + ', File: ' +str(file) + '\n' + str(chess_game[move,(rank-1),(file-1)]))



[23 22 21 17 16 18 19 20]
[24 25 26 27 28 29 30 31]
[0 0 0 0 0 0 0 0]
[0 0 0 0 0 0 0 0]
[0 0 0 0 0 0 0 0]
[0 0 0 0 0 0 0 0]
[ 8  9 10 11 12 13 14 15]
[7 6 5 1 0 2 3 4]
One-Hot for Move 0, Rank: 2, File: 1
[0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]


In [174]:
#TEST MOVE 2

chess_move = np.zeros((1, 8, 8, 32), dtype=int)

chess_move[0,0,0,7] = 1   #RA  ( 7)
chess_move[0,0,1,6] = 1   #KB  ( 6)
chess_move[0,0,2,5] = 1   #BC  ( 5)
chess_move[0,0,3,1] = 1   #Q   ( 1)
chess_move[0,0,4,0] = 1   #K   ( 0)
chess_move[0,0,5,2] = 1   #BF  ( 2)
chess_move[0,0,6,3] = 1   #KG  ( 3)
chess_move[0,0,7,4] = 1   #RH  ( 4)
chess_move[0,3,0,8] = 1   #PA  ( 8)
chess_move[0,1,1,9] = 1   #PB  ( 9)
chess_move[0,1,2,10] = 1  #PC  (10)
chess_move[0,1,3,11] = 1  #PD  (11)
chess_move[0,1,4,12] = 1  #PE  (12)
chess_move[0,1,5,13] = 1  #PF  (13)
chess_move[0,1,6,14] = 1  #PG  (14)
chess_move[0,1,7,15] = 1  #PH  (15)

# BLACK PIECES - STARTING POSITION
chess_move[0,7,0,23] = 1  #RA  (23)
chess_move[0,7,1,22] = 1  #KB  (22)
chess_move[0,7,2,21] = 1  #BC  (21)
chess_move[0,7,3,17] = 1  #Q   (17)
chess_move[0,7,4,16] = 1  #K   (16)
chess_move[0,7,5,18] = 1  #BF  (18)
chess_move[0,7,6,19] = 1  #KG  (19)
chess_move[0,7,7,20] = 1  #RH  (20)
chess_move[0,6,0,24] = 1  #PA  (24)
chess_move[0,6,1,25] = 1  #PB  (25)
chess_move[0,6,2,26] = 1  #PC  (26)
chess_move[0,6,3,27] = 1  #PD  (27)
chess_move[0,6,4,28] = 1  #PE  (28)
chess_move[0,6,5,29] = 1  #PF  (29)
chess_move[0,6,6,30] = 1  #PG  (30)
chess_move[0,6,7,31] = 1  #PH  (31)

In [175]:
#  Append the move to the chess_game.

chess_game = np.append(chess_game, chess_move, axis=0)

In [177]:
#  Some testing code.
#  Set these parameters and run the cell.
move = 2
rank = 4
file = 1


chess_game_class = np.argmax(chess_game, axis=-1)
print(chess_game_class[move,7])
print(chess_game_class[move,6])
print(chess_game_class[move,5])
print(chess_game_class[move,4])
print(chess_game_class[move,3])
print(chess_game_class[move,2])
print(chess_game_class[move,1])
print(chess_game_class[move,0])

print('One-Hot for Move ' +str(move) + ', Rank: ' +str(rank) + ', File: ' +str(file) + '\n' + str(chess_game[move,(rank-1),(file-1)]))


[23 22 21 17 16 18 19 20]
[24 25 26 27 28 29 30 31]
[0 0 0 0 0 0 0 0]
[0 0 0 0 0 0 0 0]
[8 0 0 0 0 0 0 0]
[0 0 0 0 0 0 0 0]
[ 0  9 10 11 12 13 14 15]
[7 6 5 1 0 2 3 4]
One-Hot for Move 2, Rank: 4, File: 1
[0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
